<?php
/**
 * Created by PhpStorm.
 * User: amdin
 * Date: 2017/7/24
 * Time: 10:34
 */
namespace PrjCronds\Standalone;

use Sooh2\Crond\Task;

class CheckOrders extends Task
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->toBeContinue = false;
        $this->ret = new \Sooh2\Crond\Ret();
    }


    public function free()
    {
        parent::free(); // TODO: Change the autogenerated stub
    }


    /**
     * 
     * @param \Sooh2\Crond\Time $dt
     * @return boolean
     */
    public function onRun($dt)
    {

        if($this->_isManual || $dt->hour == 3){

            $ctrl = new \Rpt\OrderCheck\Investor\OdrChkTask();
            $arr= $ctrl->debugDatabase();
            $ctrl->chkStepAll($dt->YmdFull,$arr);
        }
        $this->lastMsg = 'done';
        return true;
    }
}