<?php
/**
 * Created by PhpStorm.
 * User: amdin
 * Date: 2017/7/26
 * Time: 14:04
 */
namespace PrjCronds\Standalone;

use Sooh2\Crond\Task;

class SendProductMsg extends Task
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->toBeContinue=true;
        $this->_secondsRunAgain= 60 * 10;//每10分钟启动一次
        $this->_iissStartAfter = 0;//每小时00分后启动

        $this->ret = new \Sooh2\Crond\Ret();
    }

    public function free()
    {
        parent::free(); // TODO: Change the autogenerated stub
    }


    protected function onRun($dt)
    {
        if($this->_isManual){
            $m = 'manual';
        }else{
            $m = "auto";
        }

        if($this->_counterCalled==0){
            error_log("[TRace]".__CLASS__.'# first by '.$m.'@'. getmypid().' for-time='.date('y-m-d H:i:s',$dt->timestamp()).'  stepcount='.$this->_counterCalled);
        }else{
            error_log("[TRace]".__CLASS__.'# continue by '.$m.'@'. getmypid().' for-time='.date('y-m-d H:i:s',$dt->timestamp()).' stepcount='.$this->_counterCalled);
        }
        $this->lastMsg = $this->ret->toString();
        \Prj\Bll\SendProductMsg::getInstance()->crond();
        return true;
    }
}